from __future__ import annotations

try:  # pragma: no cover - package import path
    import troTHU.runtime_context as ctx
except ImportError:  # pragma: no cover - direct script fallback
    import runtime_context as ctx  # type: ignore


def __getattr__(name: str):
    return getattr(ctx, name)



def build_arg_parser() -> ctx.argparse.ArgumentParser:
    parser = ctx.argparse.ArgumentParser(description='THU TronClass auto rollcall helper')
    subcommands = parser.add_subparsers(dest='command')
    run_parser = subcommands.add_parser('run', help='啟動無 UI 監控 console')
    run_mode = run_parser.add_mutually_exclusive_group()
    run_mode.add_argument('--classic', action='store_true', help='相容舊參數；仍使用新版單視窗監控輸出')
    run_mode.add_argument('--no-input', action='store_true', help='只輸出監控事件，不監聽任意鍵開啟 config.conf')
    run_parser.add_argument('--ignore-attendance-rate-gate', action='store_true', help='忽略 15%% 簽到率門檻，偵測到點名後立即自動簽到')
    init_parser = subcommands.add_parser('init', help='run first-time setup wizard')
    init_parser.add_argument('--profile', default='', help='profile name to create or update')
    init_parser.add_argument('--user', default='', help='student id')
    init_parser.add_argument('--password', default='', help='password; omit to prompt securely')
    init_parser.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='config', help='where to store the password')
    init_parser.add_argument('--label', default='', help='optional display label')
    init_parser.add_argument('--telegram-token', default='', help='Telegram bot token')
    init_parser.add_argument('--telegram-chat', default='', help='Telegram chat id')
    init_parser.add_argument('--discord-token', default='', help='Discord bot token')
    init_parser.add_argument('--discord-chat', default='', help='Discord channel id')
    init_parser.add_argument('--test-login', action='store_true', help='verify login without checking rollcalls')
    init_parser.add_argument('--dry-run', action='store_true', help='show planned changes without saving')
    init_parser.add_argument('--yes', action='store_true', help='accept defaults for omitted interactive answers')
    init_parser.add_argument('--json', action='store_true', help='print machine-readable output')
    status_parser = subcommands.add_parser('status', help='show local configuration status')
    status_parser.add_argument('--json', action='store_true', help='print JSON')
    doctor_parser = subcommands.add_parser('doctor', help='run local non-network diagnostics')
    doctor_parser.add_argument('--json', action='store_true', help='print JSON')
    doctor_parser.add_argument('--probe-url', default='', help='optional HTTP URL to probe; off by default')
    doctor_parser.add_argument('--probe-count', type=int, default=3, help='optional probe attempt count')
    doctor_parser.add_argument('--probe-concurrency', type=int, default=1, help='optional probe concurrency')
    config_parser = subcommands.add_parser('config', help='查看與整理人性化 config.conf')
    config_subcommands = config_parser.add_subparsers(dest='config_command')
    config_show = config_subcommands.add_parser('show', help='顯示精簡設定摘要')
    config_show.add_argument('--json', action='store_true', help='print JSON')
    config_compact = config_subcommands.add_parser('compact', help='將 config.conf 整理成精簡格式')
    compact_mode = config_compact.add_mutually_exclusive_group()
    compact_mode.add_argument('--dry-run', action='store_true', help='只預覽，不寫入')
    compact_mode.add_argument('--write', action='store_true', help='備份後寫入精簡格式')
    config_compact.add_argument('--json', action='store_true', help='print JSON')
    config_doctor = config_subcommands.add_parser('doctor', help='檢查 config.conf 常見輸入問題')
    config_doctor.add_argument('--json', action='store_true', help='print JSON')
    config_advanced = config_subcommands.add_parser('advanced', help='用舊版記事本開啟 config.advanced.toml')
    config_advanced.add_argument('--json', action='store_true', help='print JSON')
    package_check_parser = subcommands.add_parser('package-check', help='run packaging and bundle diagnostics')
    package_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_check_parser = subcommands.add_parser('release-check', help='run release readiness checks')
    release_check_parser.add_argument('--dist', default='', help='optional dist artifact or directory to inspect')
    release_check_parser.add_argument('--plan', action='store_true', help='include non-executing release build plan')
    release_check_parser.add_argument('--json', action='store_true', help='print JSON')
    release_build_parser = subcommands.add_parser('release-build', help='run safe local release build pipeline')
    release_build_mode = release_build_parser.add_mutually_exclusive_group()
    release_build_mode.add_argument('--dry-run', action='store_true', help='print release build plan without building')
    release_build_mode.add_argument('--execute', action='store_true', help='run tests, PyInstaller, zip packaging, and smoke')
    release_build_parser.add_argument('--dist', default='', help='dist directory for artifact output')
    release_build_parser.add_argument('--work', default='', help='work directory for build and smoke temp files')
    release_build_parser.add_argument('--json', action='store_true', help='print JSON')
    provider_parser = subcommands.add_parser('provider', help='inspect TronClass provider support')
    provider_subcommands = provider_parser.add_subparsers(dest='provider_command')
    provider_list = provider_subcommands.add_parser('list', help='list supported providers')
    provider_list.add_argument('--json', action='store_true', help='print JSON')
    provider_list.add_argument('--all', action='store_true', help='include hidden/internal providers')
    provider_show = provider_subcommands.add_parser('show', help='show one provider')
    provider_show.add_argument('name', nargs='?', default='', help='provider key; defaults to active')
    provider_show.add_argument('--json', action='store_true', help='print JSON')
    app_parser = subcommands.add_parser('app', help='inspect future App/GUI architecture contracts')
    app_subcommands = app_parser.add_subparsers(dest='app_command')
    app_blueprint = app_subcommands.add_parser('blueprint', help='print future App/GUI blueprint')
    app_blueprint.add_argument('--json', action='store_true', help='print JSON')
    app_serve = app_subcommands.add_parser('serve', help='start optional localhost companion shell')
    app_serve.add_argument('--host', default='127.0.0.1', help='host to bind; defaults to localhost')
    app_serve.add_argument('--port', type=int, default=8790, help='port to bind')
    app_serve.add_argument('--open', action='store_true', help='open the local shell in the default browser')
    app_serve.add_argument('--ttl-seconds', type=int, default=900, help='local token lifetime')
    app_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    webview_parser = subcommands.add_parser('webview', help='inspect or import WebView login cookies')
    webview_subcommands = webview_parser.add_subparsers(dest='webview_command')
    webview_status = webview_subcommands.add_parser('status', help='show WebView cookie sync gates')
    webview_status.add_argument('--json', action='store_true', help='print JSON')
    webview_preview = webview_subcommands.add_parser('preview', help='preview a WebView cookie export')
    webview_preview.add_argument('--input', required=True, help='JSON cookie export path')
    webview_preview.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_preview.add_argument('--json', action='store_true', help='print JSON')
    webview_import = webview_subcommands.add_parser('import', help='import accepted cookies into cookie cache')
    webview_import.add_argument('--input', required=True, help='JSON cookie export path')
    webview_import.add_argument('--profile', default='', help='profile name; defaults to active')
    webview_import.add_argument('--save', action='store_true', help='write accepted cookies to local cookie cache')
    webview_import.add_argument('--json', action='store_true', help='print JSON')
    courses_parser = subcommands.add_parser('courses', help='discover current semester and courses')
    courses_parser.add_argument('--json', action='store_true', help='print JSON')
    teacher_parser = subcommands.add_parser('teacher', help='teacher-side rollcall tools')
    teacher_subcommands = teacher_parser.add_subparsers(dest='teacher_command')
    teacher_rollcall = teacher_subcommands.add_parser('rollcall', help='create, start, or stop teacher rollcalls')
    teacher_rollcall_subcommands = teacher_rollcall.add_subparsers(dest='teacher_rollcall_command')
    teacher_rollcall_create = teacher_rollcall_subcommands.add_parser('create', help='create a teacher rollcall')
    teacher_rollcall_create.add_argument('--course-id', required=True, help='course id')
    teacher_rollcall_create.add_argument('--type', choices=('manual', 'number', 'radar', 'qr', 'self_registration'), default='manual', help='rollcall type')
    teacher_rollcall_create.add_argument('--start', action='store_true', help='start after creating')
    teacher_rollcall_create.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_start = teacher_rollcall_subcommands.add_parser('start', help='start a rollcall')
    teacher_rollcall_start.add_argument('rollcall_id')
    teacher_rollcall_start.add_argument('--duration-seconds', type=int, default=0, help='optional duration in seconds')
    teacher_rollcall_start.add_argument('--duration-min', type=int, default=0, help='optional duration in minutes')
    teacher_rollcall_start.add_argument('--json', action='store_true', help='print JSON')
    teacher_rollcall_stop = teacher_rollcall_subcommands.add_parser('stop', help='stop a rollcall')
    teacher_rollcall_stop.add_argument('rollcall_id')
    teacher_rollcall_stop.add_argument('--type', choices=('manual', 'number', 'radar', 'qr', 'self_registration'), required=True, help='rollcall type used to choose the stop endpoint')
    teacher_rollcall_stop.add_argument('--json', action='store_true', help='print JSON')
    subcommands.add_parser('refresh', help='delete cached cookies for the active profile')
    dashboard_parser = subcommands.add_parser('dashboard', help='show a lightweight terminal dashboard')
    dashboard_parser.add_argument('--once', action='store_true', help='render once and exit')
    dashboard_parser.add_argument('--interval', type=float, default=2.0, help='refresh interval seconds')
    dashboard_parser.add_argument('--json', action='store_true', help='print one machine-readable snapshot')
    debug_parser = subcommands.add_parser('debug-capture', help='capture one sanitized rollcall API snapshot for diagnostics')
    debug_parser.add_argument('--output', default='', help='JSONL output path; defaults to state/debug-capture/rollcalls.jsonl')
    research_parser = subcommands.add_parser('research', help='run opt-in research diagnostics')
    research_subcommands = research_parser.add_subparsers(dest='research_command')
    research_status = research_subcommands.add_parser('status', help='show research mode gates')
    research_status.add_argument('--json', action='store_true', help='print JSON')
    research_api = research_subcommands.add_parser('api', help='capture sanitized read-only API metadata')
    research_api.add_argument('--target', default='all', help='safe target: home, rollcalls, semester, courses, or all')
    research_api.add_argument('--output', default='', help='optional JSONL output path')
    research_api.add_argument('--json', action='store_true', help='print JSON')
    research_probe = research_subcommands.add_parser('probe', help='probe risky endpoints as sanitized read-only shape metadata')
    research_probe.add_argument('probe_target', nargs='?', default='student_rollcalls', help='probe target: student_rollcalls, lite, or ongoing_rollcalls')
    research_probe.add_argument('--rollcall-id', default='', help='rollcall id to probe (required for student_rollcalls and lite; ignored for ongoing_rollcalls)')
    research_probe.add_argument('--output', default='', help='optional JSONL output path')
    research_probe.add_argument('--json', action='store_true', help='print JSON')
    research_browser_check = research_subcommands.add_parser('browser-check', help='check optional Playwright availability')
    research_browser_check.add_argument('--json', action='store_true', help='print JSON')
    research_browser_capture = research_subcommands.add_parser('browser-capture', help='capture sanitized browser request metadata without logging in')
    research_browser_capture.add_argument('--target', choices=('login', 'home'), default='home')
    research_browser_capture.add_argument('--json', action='store_true', help='print JSON')
    qr_parser = subcommands.add_parser('qr', help='submit, preview, or scan TronClass QR payloads')
    qr_parser.add_argument('qr_args', nargs='*', help='payload, or subcommands: paste/pending/scan')
    qr_parser.add_argument('--yes', action='store_true', help='skip QR paste confirmation')
    qr_parser.add_argument('--all', dest='fanout_all', action='store_true', help='submit to all matching pending profiles')
    qr_parser.add_argument('--json', action='store_true', help='print JSON for preview/pending')
    qr_parser.add_argument('--host', default='', help='local scanner host')
    qr_parser.add_argument('--port', type=int, default=0, help='local scanner port')
    qr_parser.add_argument('--open', action='store_true', help='open local scanner in browser')
    qr_parser.add_argument('--image', default='', help='decode QR payload from a static image file')
    logs_parser = subcommands.add_parser('logs', help='inspect sanitized local logs')
    logs_subcommands = logs_parser.add_subparsers(dest='logs_command')
    logs_tail = logs_subcommands.add_parser('tail', help='print recent JSONL log records')
    logs_tail.add_argument('--limit', type=int, default=20)
    logs_tail.add_argument('--json', action='store_true')
    logs_summary = logs_subcommands.add_parser('summarize', help='summarize log records')
    logs_summary.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary.add_argument('--json', action='store_true')
    logs_summary_alias = logs_subcommands.add_parser('summary', help='alias for summarize')
    logs_summary_alias.add_argument('--limit', type=int, default=20, help='recent records to include in notable event summary')
    logs_summary_alias.add_argument('--json', action='store_true')
    logs_export = logs_subcommands.add_parser('export', help='write a redacted debug bundle')
    logs_export.add_argument('--output', default='', help='output zip path')
    logs_export.add_argument('--json', action='store_true')
    logs_export.add_argument('--limit', type=int, default=50)
    account_parser = subcommands.add_parser('account', help='manage account profiles')
    account_subcommands = account_parser.add_subparsers(dest='account_command')
    account_list = account_subcommands.add_parser('list', help='list account profiles')
    account_list.add_argument('--json', action='store_true')
    account_show_parser = account_subcommands.add_parser('show', help='show one account profile')
    account_show_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_show_parser.add_argument('--json', action='store_true')
    account_state_parser = account_subcommands.add_parser('state', help='show runtime state for one account profile')
    account_state_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_state_parser.add_argument('--json', action='store_true')
    account_doctor_parser = account_subcommands.add_parser('doctor', help='diagnose one account profile')
    account_doctor_parser.add_argument('name', nargs='?', default='', help='profile name; defaults to active')
    account_doctor_parser.add_argument('--json', action='store_true')
    account_add = account_subcommands.add_parser('add', help='add or update an account profile')
    account_add.add_argument('name', help='profile name')
    account_add.add_argument('--user', help='student id')
    account_add.add_argument('--password', help='password; omit to prompt securely')
    account_add.add_argument('--store', choices=('keyring', 'env', 'config', 'none'), default='config', help='where to store the password')
    account_add.add_argument('--label', default='', help='optional display label')
    account_add.add_argument('--no-switch', action='store_true', help='do not switch to this profile')
    account_switch = account_subcommands.add_parser('switch', help='switch active profile')
    account_switch.add_argument('name', help='profile name')
    account_remove = account_subcommands.add_parser('remove', help='remove an account profile')
    account_remove.add_argument('name', help='profile name')
    account_bind = account_subcommands.add_parser('bind', help='bind adapter user id to a profile')
    account_bind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_bind.add_argument('external_user_id')
    account_bind.add_argument('profile')
    account_bind.add_argument('--channel', default='')
    account_unbind = account_subcommands.add_parser('unbind', help='remove adapter binding')
    account_unbind.add_argument('adapter', choices=('discord', 'line', 'telegram'))
    account_unbind.add_argument('external_user_id')
    bot_parser = subcommands.add_parser('bot', help='run bot adapter services')
    bot_subcommands = bot_parser.add_subparsers(dest='bot_command')
    bot_serve = bot_subcommands.add_parser('serve', help='serve bot adapter webhooks')
    bot_serve.add_argument('--host', default='127.0.0.1', help='bind host')
    bot_serve.add_argument('--port', type=int, default=8787, help='bind port')
    bot_serve.add_argument('--adapter', choices=('all', 'generic', 'line', 'discord'), default='all')
    bot_serve.add_argument('--json', action='store_true', help='print startup metadata as JSON')
    bot_schema = bot_subcommands.add_parser('discord-schema', help='print Discord slash command schema')
    bot_schema.add_argument('--json', action='store_true', help='print schema as JSON')
    bot_discord_sync = bot_subcommands.add_parser('discord-sync', help='sync Discord slash command schema')
    bot_discord_sync.add_argument('--apply', action='store_true', help='apply schema to Discord; default is dry-run')
    bot_discord_sync.add_argument('--dry-run', action='store_true', help='show planned sync without network')
    bot_discord_sync.add_argument('--json', action='store_true', help='print JSON')
    bot_discord_gateway = bot_subcommands.add_parser('discord-gateway', help='run optional Discord Gateway')
    bot_discord_gateway.add_argument('--dry-run', action='store_true', help='print safe health without connecting')
    bot_discord_gateway.add_argument('--json', action='store_true', help='print JSON')
    return parser
