'use strict';

/**
 * All application constants — single source of truth.
 * Replaces duplicated constants from Python runtime_context.py and runtime_helpers.py.
 */

const NUMBER_CODE_LIMIT = 10000;
const NUMBER_WORKER_COUNT = 100;
const NUMBER_MIN_WORKER_COUNT = 5;
const NUMBER_REQUEST_RETRIES = 3;
const NUMBER_PROGRESS_INTERVAL = 0.5;
const NUMBER_COOLDOWN_SECONDS = 5.0;
const NUMBER_MAX_COOLDOWNS = 3;
const NUMBER_TRANSIENT_FAILURE_THRESHOLD = 20;
const NUMBER_TRANSIENT_FAILURE_RATIO = 0.35;

const DEFAULT_OPERATING_RANGE = ['00:00', '00:00'];

const LOGIN_RETRY_DELAYS = [10.0, 30.0, 60.0, 300.0];

const FATAL_NOTIFICATION_INTERVAL = 300.0;

const DEFAULT_HTTP_TIMEOUT_SECONDS = 20.0;
const DEFAULT_NOTIFICATION_TIMEOUT_SECONDS = 10.0;

const PLACEHOLDER_CREDENTIAL_VALUES = new Set([
  '', 'YOUR_STUDENT_ID', 'YOUR_PASSWORD', '您的學號', '您的密碼',
]);

const DEFAULT_USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edge/136.0.0.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5410.0 Safari/537.36',
  'Mozilla/5.0 (Android 10; Mobile; rv:78.0) Gecko/20100101 Firefox/78.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0',
];

module.exports = {
  NUMBER_CODE_LIMIT,
  NUMBER_WORKER_COUNT,
  NUMBER_MIN_WORKER_COUNT,
  NUMBER_REQUEST_RETRIES,
  NUMBER_PROGRESS_INTERVAL,
  NUMBER_COOLDOWN_SECONDS,
  NUMBER_MAX_COOLDOWNS,
  NUMBER_TRANSIENT_FAILURE_THRESHOLD,
  NUMBER_TRANSIENT_FAILURE_RATIO,
  DEFAULT_OPERATING_RANGE,
  LOGIN_RETRY_DELAYS,
  FATAL_NOTIFICATION_INTERVAL,
  DEFAULT_HTTP_TIMEOUT_SECONDS,
  DEFAULT_NOTIFICATION_TIMEOUT_SECONDS,
  PLACEHOLDER_CREDENTIAL_VALUES,
  DEFAULT_USER_AGENTS,
};
